# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4cfdea105f50886444d1abf3afbeb801b2e808689efc75452eb022533a3a59de360efb05b225956207d06b5f24c1c48855e809409e9ec7ec951bd1e4b610c93

test:
  secret_key_base: deee40f28b62d77fef6f1d3363224c53d545358173117a48dbcf55f1a3efc2eedc321b44ef13eb56091b9ed77c19db7a76a1ada6288a2ff36cc52b621c9c54da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
